config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/products', to: 'products#index'
  # get '/products/new', to: 'products#new', as: "new_product"
  # post '/products', to: 'products#create'
  # get '/products/:id', to: 'products#show', as: "product"
  # get '/products/:id/edit', to: 'products#edit', as: "edit_product"
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def sign_in(user)
    cookies.permanent.signed[:user_id] = user.id
    @current_user = user
  end
  
  def sign_out
    cookies.delete(:user_id)
    @current_user = nil
  end
  
  private
    def signed_in?
      !current_user.nil?
    end
    helper_method :signed_in?
  
    def current_user
      @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
    rescue ActiveRecord::RecordNotFound
    end
    helper_method :current_user

    def private_access
      redirect_to :login unless signed_in?      
    end

    def public_access
      redirect_to root_path if signed_in?      
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :private_access, except: [:index, :show]


  def index
    @products = Product.all
  end

  def new
    @product = Product.new  
  end

  def create
    @product = Product.new(product_params)
      if @product.save 
        redirect_to products_path, notice: "El producto fue publicado con éxito" 
      else
        render :new
      end  
  end

  def show
    @product = Product.find(params[:id])    
  end

  def edit
    @product = Product.find(params[:id])    
  end

  def update
    product = Product.find(params[:id]) 
      if product.update(product_params)
        redirect_to products_path, notice: "El producto ha sido modificado con éxito" 
      else
        render :edit
      end
  end

  def destroy
    product = Product.find(params[:id]) 
    product.destroy

    redirect_to products_path, notice: "El producto fue eliminado con éxito"

  end
  
  
  private

  def product_params
    params.require(:product).permit(:name, :url, :description)  
  end

end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :private_access, only: [:destroy]
  before_action :public_access, except: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :twitter_handle)
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title
   @product.new_record? ? "Publicar Producto" : "Modificar Producto"
  end  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">        
          <%= link_to "Product Hunt", root_path, class: "navbar-brand" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </ul>
        <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class=" avatar">
                <img src="<%= Gravatar.new("#{current_user.email}").image_url %>" class="img-circle" />                     
              </a>
            </li>
            <br>
            <li><%= link_to "Crear_Producto_", new_product_path %></li>
            <li><%= link_to "Salir", logout_path, method: :delete %></li>               
          <% else %>
            <li><%= link_to "Regístrate", new_user_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
          </ul>
      </form>
    </div>
   </nav>

    
    <% if flash[:notice] %>
      <div class="alert  alert-info"><%= flash[:notice] %></div>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col offset-sm-3">
      <h1><%= form_title %></h1>
      <%= form_for @product do |f|%>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", 
          placeholder: "Ingresa el nombre del producto"%>
        </div>

        <div class="form-group">
          <%= f.url_field :url, class: "form-control input-lg", 
          placeholder: "Ingresa la url del producto"%>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: "form-control input-lg", 
          placeholder: "Ingresa la descripción del producto"%>
        </div>

        <div class="form-group">
          <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <div class="products">
        <% @products.each do |product| %>
        <div class="product clearfix">
          <div class="product-details">
            <span class="product-title"><%= link_to product.name, product %></span>
            <span class="product-description"><%= product.description %></span>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col offset-sm-3">
      <h1>Publicar Producto</h1>
      <%= form_for @product do |f|%>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", 
          placeholder: "Ingresa el nombre del producto"%>
        </div>

        <div class="form-group">
          <%= f.url_field :url, class: "form-control input-lg", 
          placeholder: "Ingresa la url del producto"%>
        </div>

        <div class="form-group">
          <%= f.text_area :url, class: "form-control input-lg", 
          placeholder: "Ingresa la descripción del producto"%>
        </div>

        <div class="form-group">
          <%= f.submit "Publicar Producto", class: "btn btn-primary btn-lg btn-block" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="product-page">
  <header class="product-header">
    <h1><%= @product.name %></h1>
    <p><%= @product.description %></p>
    <a href="<%= @product.url %>" class="btn btn-primary btn-lg" target="_blank">¡Obtenlo!</a>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="votes">
          <h2>Votos</h2>
        </div>

        <div class="comments">
          <h2>Comentarios</h2>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Crear Cuenta</h1>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Nombre" %>
        </div>

        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="basic-addon1">@</span>
          <%= f.text_field :twitter_handle, class: "form-control input-lg", placeholder: "Twitter" %>
        </div>

        <div class="actions">
          <%= f.submit class: "btn btn-primary btn-block btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>